CURRENCY_CHOICES = (
    ("RUB", "Russian Ruble (RUB)"),
    ("USD", "US Dollar (USD)"),
    ("EUR", "Euro (EUR)"),
    ("GBP", "British Pound (GBP)"),
    ("JPY", "Japanese Yen (JPY)"),
    ("AUD", "Australian Dollar (AUD)"),
    ("CAD", "Canadian Dollar (CAD)"),
    ("CHF", "Swiss Franc (CHF)"),
    ("CNY", "Chinese Yuan (CNY)"),
    ("INR", "Indian Rupee (INR)"),
    ("BRL", "Brazilian Real (BRL)"),
    ("ZAR", "South African Rand (ZAR)"),
    ("MXN", "Mexican Peso (MXN)"),
    ("SEK", "Swedish Krona (SEK)"),
    ("NOK", "Norwegian Krone (NOK)"),
    ("DKK", "Danish Krone (DKK)"),
    ("SAR", "Saudi Riyal (SAR)"),
    ("AED", "United Arab Emirates Dirham (AED)"),
    ("TRY", "Turkish Lira (TRY)"),
    ("RMB", "Renminbi (RMB)"),
    ("HKD", "Hong Kong Dollar (HKD)"),
    ("SGD", "Singapore Dollar (SGD)"),
    ("MYR", "Malaysian Ringgit (MYR)"),
    ("THB", "Thai Baht (THB)"),
    ("PHP", "Philippine Peso (PHP)"),
    ("IDR", "Indonesian Rupiah (IDR)"),
    ("PLN", "Polish Zloty (PLN)"),
    ("HUF", "Hungarian Forint (HUF)"),
    ("CZK", "Czech Koruna (CZK)"),
    ("ISK", "Icelandic Krona (ISK)"),
    ("KWD", "Kuwaiti Dinar (KWD)"),
    ("BHD", "Bahraini Dinar (BHD)"),
    ("OMR", "Omani Rial (OMR)"),
    ("QAR", "Qatari Rial (QAR)"),
    ("LKR", "Sri Lankan Rupee (LKR)"),
    ("VND", "Vietnamese Dong (VND)"),
    ("NGN", "Nigerian Naira (NGN)"),
    ("KES", "Kenyan Shilling (KES)"),
    ("EGP", "Egyptian Pound (EGP)"),
    ("MAD", "Moroccan Dirham (MAD)"),
    ("ARS", "Argentine Peso (ARS)"),
    ("CLP", "Chilean Peso (CLP)"),
    ("COP", "Colombian Peso (COP)"),
    ("PEN", "Peruvian Nuevo Sol (PEN)"),
    ("UYU", "Uruguayan Peso (UYU)"),
    ("MXN", "Mexican Peso (MXN)"),
    ("GHS", "Ghanaian Cedi (GHS)"),
    ("AED", "United Arab Emirates Dirham (AED)"),
)

LANGUAGE_CHOICES = (
    ("RUSSIAN", "Russian"),
    ("ENGLISH", "English"),
    ("SPANISH", "Spanish"),
    ("FRENCH", "French"),
    ("GERMAN", "German"),
    ("CHINESE", "Chinese"),
    ("JAPANESE", "Japanese"),
    ("ITALIAN", "Italian"),
    ("PORTUGUESE", "Portuguese"),
    ("ARABIC", "Arabic"),
    ("KOREAN", "Korean"),
    ("HINDI", "Hindi"),
    ("BENGALI", "Bengali"),
    ("TURKISH", "Turkish"),
    ("POLISH", "Polish"),
    ("DUTCH", "Dutch"),
    ("SWEDISH", "Swedish"),
    ("NORWEGIAN", "Norwegian"),
    ("DANISH", "Danish"),
    ("FINNISH", "Finnish"),
    ("ROMANIAN", "Romanian"),
    ("GREEK", "Greek"),
    ("CZECH", "Czech"),
    ("HUNGARIAN", "Hungarian"),
    ("HEBREW", "Hebrew"),
    ("THAI", "Thai"),
    ("VIETNAMESE", "Vietnamese"),
    ("INDONESIAN", "Indonesian"),
    ("MALAY", "Malay"),
    ("TAMIL", "Tamil"),
    ("TELUGU", "Telugu"),
    ("MARATHI", "Marathi"),
    ("KANNADA", "Kannada"),
    ("GUJARATI", "Gujarati"),
    ("PUNJABI", "Punjabi"),
    ("UKRAINIAN", "Ukrainian"),
    ("BULGARIAN", "Bulgarian"),
    ("SERBIAN", "Serbian"),
    ("CROATIAN", "Croatian"),
    ("SLOVAK", "Slovak"),
    ("SLOVENIAN", "Slovenian"),
    ("LATVIAN", "Latvian"),
    ("LITHUANIAN", "Lithuanian"),
    ("ESTONIAN", "Estonian"),
    ("ALBANIAN", "Albanian"),
    ("MACEDONIAN", "Macedonian"),
    ("MONTENEGRIN", "Montenegrin"),
    ("GEORGIAN", "Georgian"),
    ("AZERBAIJANI", "Azerbaijani"),
    ("ARMENIAN", "Armenian"),
    ("KAZAKH", "Kazakh"),
    ("UZBEK", "Uzbek"),
    ("TURKMEN", "Turkmen"),
    ("KYRGYZ", "Kyrgyz"),
    ("TAJIK", "Tajik"),
    ("MONGOLIAN", "Mongolian"),
    ("NEPALI", "Nepali"),
    ("BOSNIAN", "Bosnian"),
    ("MACEDONIAN", "Macedonian"),
    ("SINHALESE", "Sinhalese"),
    ("LAO", "Lao"),
)

PRODUCT_ATTRIBUTE_CHOICES = (
    ("BRAND_NAME", "Brand Name"),
    ("MODEL_NUMBER", "Model Number"),
    ("ORIGIN", "Origin"),
    ("APPLICABLE_PEOPLE", "Applicable People"),
    ("APPLICATION", "Application"),
    ("FEATURES", "Features"),
    ("WARRANTY", "Warranty Period"),
    ("DELIVERY_TIME", "Delivery Time"),
    ("PACKAGE", "Package"),
    ("CERTIFICATION", "Certification"),
    ("TYPE", "Type"),
    ("PROGRAMMABLE", "Programmable"),
    ("PRODUCT_NAME", "Product Name"),
    ("WEIGHT", "Weight"),
    ("DIMENSION", "Dimension"),
    ("SIZE", "Size"),
    ("MATERIAL", "Material"),
    ("COLOR", "Color"),
    ("STITCHING_TYPE", "Stitching Type"),
    ("STYLE", "Style"),
    ("FITTING_TYPE", "Fitting Type"),
    ("GENDER", "Gender"),
    ("SEASON", "Season"),
    ("FABRIC_TYPE", "Fabric Type"),
    ("CARE_INSTRUCTIONS", "Care Instructions"),
    ("SCREEN_SIZE", "Screen Size"),
    ("PROCESSOR_TYPE", "Processor Type"),
    ("BATTERY_LIFE", "Battery Life"),
    ("OPERATING_SYSTEM", "Operating System"),
    ("RAM_SIZE", "RAM Size"),
    ("STORAGE_CAPACITY", "Storage Capacity"),
    ("CAMERA_RESOLUTION", "Camera Resolution"),
    ("CONNECTIVITY", "Connectivity"),
    ("WIFI_SUPPORT", "Wi-Fi Support"),
    ("BLUETOOTH_SUPPORT", "Bluetooth Support"),
    ("USB_PORTS", "USB Ports"),
    ("CHARGING_TYPE", "Charging Type"),
    ("DISPLAY_TYPE", "Display Type"),
    ("SPEAKER_TYPE", "Speaker Type"),
    ("GPS_SUPPORT", "GPS Support"),
    ("SIM_CARD_TYPE", "SIM Card Type"),
    ("WATER_RESISTANT", "Water Resistant"),
    ("GRAPHICS_CARD", "Graphics Card"),
    ("RAM", "RAM"),
    ("STORAGE_TYPE", "Storage Type"),
    ("SCREEN_RESOLUTION", "Screen Resolution"),
    ("CPU_SPEED", "CPU Speed"),
    ("COOLING_SYSTEM", "Cooling System"),
    ("PORTS", "Ports"),
    ("DISPLAY_SIZE", "Display Size"),
    ("COLOR_SCHEME", "Color Scheme"),
    ("RESOLUTION", "Resolution"),
    ("TEXTURE", "Texture"),
    ("FRAME_MATERIAL", "Frame Material"),
    ("LENS_MATERIAL", "Lens Material"),
    ("LENS_COLOR", "Lens Color"),
    ("UV_PROTECTION", "UV Protection"),
    ("FRAME_TYPE", "Frame Type"),
    ("CHEMICAL_COMPOSITION", "Chemical Composition"),
    ("USAGE", "Usage"),
    ("STORAGE_CONDITIONS", "Storage Conditions"),
    ("SAFETY_PRECAUTIONS", "Safety Precautions"),
    ("PACKAGING", "Packaging"),
    ("COMPATIBILITY", "Compatibility"),
    ("AGE_RANGE", "Age Range"),
    ("BATTERY_REQUIREMENTS", "Battery Requirements"),
    ("SAFETY_CERTIFICATIONS", "Safety Certifications"),
    ("ASSEMBLY_REQUIRED", "Assembly Required"),
    ("CAPACITY", "Capacity"),
    ("CUSHION_MATERIAL", "Cushion Material"),
    ("FOOT_TYPE", "Foot Type"),
    ("MAX_WEIGHT_CAPACITY", "Max Weight Capacity"),
    ("USE_CASE", "Use Case"),
    ("POWER_CONSUMPTION", "Power Consumption"),
    ("ENERGY_RATING", "Energy Rating"),
    ("SAFETY_FEATURES", "Safety Features"),
    ("TEMPERATURE_RANGE", "Temperature Range"),
    ("FUNCTIONALITY", "Functionality"),
    ("SUITABILITY", "Suitability"),
    ("ACCESSORIES_INCLUDED", "Accessories Included"),
    ("TUNING", "Tuning"),
)